# Generated by Django 6.0.6 on 2026-06-04 14:27

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('1_1', 'Year 1 - Semester 1'), ('1_2', 'Year 1 - Semester 2'), ('2_1', 'Year 2 - Semester 1'), ('2_2', 'Year 2 - Semester 2'), ('3_1', 'Year 3 - Semester 1'), ('3_2', 'Year 3 - Semester 2'), ('4_1', 'Year 4 - Semester 1'), ('4_2', 'Year 4 - Semester 2')], max_length=5)),
                ('resource_type', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('assignment', 'Assignment'), ('past_paper', 'Past Paper'), ('tutorial', 'Tutorial'), ('project_report', 'Project Report'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('file', models.FileField(blank=True, help_text='Temporary local file — will be moved to Azure Blob Storage', upload_to=resources.models.resource_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('view', 'View'), ('delete', 'Delete'), ('share', 'Share'), ('login', 'Login')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='resources.resource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course'], name='resources_r_course_5afae2_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['semester'], name='resources_r_semeste_f41a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploaded_by'], name='resources_r_uploade_6765b4_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='resources_r_created_83a7af_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='resources_a_user_id_4f3544_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='resources_a_action_55c2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='resources_a_timesta_e7317b_idx'),
        ),
    ]
